[package]
name = "bevy_swash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"bevy" = "0.13.1"
"bevy_utils" = "0.13.1"
"swash" = "0.1.13"
"thiserror" = "1.0"